---
- name: Install node and npm
  hosts: ubuntu_servers
  become: True
  tasks:
    - name: Update apt repo and cache
      ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      ansible.builtin.apt:
        pkg:
          - nodejs
          - npm
          - net-tools
          - acl

- name: Create new linux user for node app
  hosts: ubuntu_servers
  become: True
  tasks:
    - name: Create linux user
      ansible.builtin.user:
        name: node
        comment: Node user
        group: ubuntu


- name: Deploy nodejs app
  hosts: ubuntu_servers
  become: True
  become_user: node
  vars_files:
    - project-vars
  tasks:
    - name: Unpack tgz file
      ansible.builtin.unarchive:
        src: "{{location}}/nodejs-app-1.0.0.tgz"
        dest: "{{home_dir}}"
    - name: Install dependencies
      community.general.npm:
        path: "{{home_dir}}/package"
    - name: Start the app
      ansible.builtin.command:
        chdir: "{{home_dir}}/package/app"
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      ansible.builtin.shell: ps aux | grep node
      register: app_status
    - ansible.builtin.debug: msg={{app_status.stdout_lines}}

